spring:
    application:
        name: pitterpatter

    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://mysql:3306/pitterpatter?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
        username: ssafy
        password: asdzxcfv10

    jpa:
        # true ??? JPA ??? ?? ??
        show-sql: true
        hibernate:
            # DB ???? ??? ?? ??? ???? ?? ??? ?? [ ???? ?? ?? CREATE ]
            ddl-auto: update
        properties:
            hibernate:
                # JPA? ???? Hibernate? ????? ??? SQL? ???? ????.
                format_sql: true

<<<<<<< HEAD
jasypt:
    encryptor:
        bean: jasyptStringEncryptor

logging:
    level:
        com.pitpat: DEBUG

jwt:
    header: Authorization
    # jwt secret key를 jasypt secret key로 암호화함.
    secret: ENC(WOYtLPTiMRjjiLX6WN3SREANUKLm2o1d2R/WPzTYEiJ0sEA6XFK8evCage9kSKUHuPHafl2LuENJXFVqn2hjcypolp8hE/FVaSza4iLTXFMTnvc4hDhpgQ==)
    token-validity-in-seconds: 86400
