spring:
  application:
    name: pitterpatter
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/pitterpatter?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: ssafy
    password: asdzxcfv10

  jpa:
    open-in-view: true
    # true ??? JPA ??? ?? ??
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        # JPA? ???? Hibernate? ????? ??? SQL? ???? ????.
        format_sql: true
