apiVersion: apps/v1
kind: Deployment
metadata:
  name: child
  namespace: pitter-patter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: child
  template:
    metadata:
      labels:
        app: child
    spec:
      containers:
      - name: child
        image: tkdqja9573/ssafy-common-child:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: child
  namespace: pitter-patter
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: child